require:
  - rubocop-performance

AllCops:
  # Ruby 3.0
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - spec/**/*

Layout/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 20
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Max: 20
Style/FormatString:
  EnforcedStyle: percent
Style/FormatStringToken:
  MaxUnannotatedPlaceholdersAllowed: 3
Style/HashLikeCase:
  MinBranchesCount: 4
