name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1.2'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the spec task
      run: bundle exec rake spec

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        # Ruby 2.7
        ruby-version: 2.7
        bundler-cache: true
    - name: Run the rubocop task
      run: |
        bundle add code-scanning-rubocop --version '= 0.5.0' --source 'https://rubygems.org'
        bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif lib/
    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: rubocop.sarif
